config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies, only: [:new, :create, :destroy, :index, :edit]
  resources :context
  resources :users
  resources :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :admin

  get   'movies/own'  => 'movies#own'
  get   'movies/search' => 'movies#search'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/reset',   to: 'movies#reset',         via: 'get'
  match '/stepup',  to: 'sessions#stepup',      via: 'get'
  match '/suggested', to: 'context#suggested',  via: 'get'
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :signed_in_user, only: [:new, :own]

	def new
		@movie = Movie.new
	end

	def index

		@id = Movie.sorteer_decide_i(params[:sorteer])
		@title = Movie.sorteer_decide_t(params[:sorteer])
		@rating = Movie.sorteer_decide_r(params[:sorteer])
		@username = Movie.sorteer_decide_u(params[:sorteer])

		if signed_in?
			@own_movies = Movie.where(user_id: current_user.id)
		end

		if params[:sorteer].present?
			@movies = Movie.sorteer(params[:sorteer])
		else
			@movies = Movie.order('id ASC')
		end

		if params[:url].present?
			movie = Movie.find(params[:id])
			movie.imdb = params[:url]
			movie.title = params[:title]
			movie.save
			redirect_to '/movies/'
		end
	end

	def show
		@movie = Movie.find(params[:id])
	end

	def create
		swap_date(movie_params)
		@movie = Movie.new(movie_params)
		@movie[:user_id] = current_user.id
		if @movie.save
			redirect_to '/movies/'
		else
			render 'new'
		end
	end

	def own
		@movies = Movie.where(user_id: current_user.id)
		if @movies.nil?
			@movies = @movie.order('rating DESC')
		end
	end

	def search
		bf = BadFruit.new("7y3ev7dshky24eynky3apa4m")
		@result = bf.movies.search_by_name(params[:title], 10)
	end

	def destroy
		Movie.find(params[:id]).destroy
		redirect_to '/movies/'

	end

	def reset
		Movie.delete_all
		User.delete_all

		redirect_to root_url
	end

	private

		def movie_params
			params.require(:movie).permit(:title, :rating, :saw_movie_at, :comment, :user_id, :imdb)
		end

		def swap_date(movie_params)
			temp = movie_params["saw_movie_at(1i)"]
			movie_params["saw_movie_at(1i)"] = movie_params["saw_movie_at(3i)"]
			movie_params["saw_movie_at(3i)"] = temp
			movie_params
		end

		def signed_in_user
			redirect_to signin_url unless signed_in?
		end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<center>
  <% if @movies.empty? %>
    Geen films in database <br />
  <% else %>

  <table class="table table-striped">

    <tr class="info">
      <th>
          <%= link_to "Id", movies_path(:sorteer => @id) %>
      </th>
      <th>
          <%= link_to "Title", movies_path(:sorteer => @title) %>
      </th>
      <th>
          <%= link_to "Rating", movies_path(:sorteer => @rating) %>
      </th>
      <th>
          <%= link_to "Added by", movies_path(:sorteer => @username) %>
      </th>

      <% if signed_in? && current_user.admin? %>

        <th>Actions</th>

      <% end %>

    </tr>

    <% @movies.each do |film| %>

    <tr>
      <td><%= film.id %></td>
      <td>

      <%if film.imdb.nil? %> 

        <%= film.title %> - <%= link_to "Add imdb link", movies_search_path(:title => film.title, :id => film.id) %>

      <% else %>

        <%= link_to "#{film.title}", film.imdb, :target => 'blank'%>

      <% end %>

      </td>
      <td><%= film.rating %></td>
      <td><%= film.user.username %></td>      

      <% if signed_in? && current_user.admin? %>

        <td>
        <div style="float:left;">
          <%= link_to "Edit", edit_movie_path(film), :class => "btn btn-warning" %>
        </div>
        <div style="float:right;">        
          <%= button_to "Delete", film, method: :delete, :class => "btn btn-danger" %> 
        </td>
      
      <% end %>     
    </tr>

    <% end %>

  </table>

<% end %>
<br /> <br />
<%= debug(params) if Rails.env.development? %>

</center>

app/views/movies/new.html.erb
<div class = "testbox">
<center>

	<h1>Add a movie</h1>
	<%= form_for @movie do |f| %>
	  	<%= f.text_field :title, :placeholder => "Title" %> <br /><br />

	  	<%= f.text_field :rating, :placeholder => "Rating out of 10" %> <br /><br />

	  	<%= f.label :Visited_at %><br />
	  	<%= f.date_select(:saw_movie_at, order: [:day, :month, :year]) %> <br /><br />

	  <%= f.submit "Create" %>
	<% end %>

</center>
</div>

app/views/movies/own.html.erb
<center>

	<h1>Welcome to MovieTrackr</h1>
	<% if signed_in? %>
	  <h2>Hello, <%= current_user.username %>!</h2>
	<% end %>
	<br />
	<br />

<% if @movies.empty? %>
	Geen films in database
<% else %>

	<table class="table table-striped">

		<tr class="info">
			<th>ID</th>
			<th>Title</th>
			<th>Rating</th>
			<th>Actions</th>
		</tr>

		<% @movies.each do |film| %>

			<tr>
				<td><%= film.id %></td>
				<td><%= film.title %></td>	
				<td><%= film.rating %></td>
				<td>
					<%= link_to "delete", film, method: :delete %> -
					<%= link_to "edit", edit_movie_path(film) %>
				</td>						
			</tr>

		<% end %>

	</table>

<% end %>
</center>

app/views/movies/search.html.erb
<center>
<h2>Search results for '<%= params[:title] %>'</h2>

<table class="table table-striped">

	<tr class="info">
	      <th>
	        Poster
	      </th>
	      <th>
	      	Title
	      </th>
	      <th>
	      	Url
	      <th>
	          Action
	      </th>
	</tr>

	<% @result.each do |movie| %>

	<tr>
		<td>
		<%= image_tag(movie.posters.thumbnail) %>
		</td>
		<td>
		<%= movie.name %>
		</td>
		<td>
		<%= link_to "RottenTomatoes", movie.links['alternate'], :target => "_blank" %>
		</td>
		<td>
		<%= link_to "Add link", movies_path(:url => movie.links['alternate'], :id => params[:id], :title => movie.name) %>
		</td>
	</tr>

	<% end %>

</table>



<%= debug(params) if Rails.env.development? %>	

app/views/movies/show.html.erb
<%= @movie.title %>