config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies, only: [:new, :create, :destroy, :index, :edit]
  resources :context
  resources :users
  resources :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :admin

  get   'movies/own'  => 'movies#own'
  get   'movies/search' => 'movies#search'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/reset',   to: 'movies#reset',         via: 'get'
  match '/stepup',  to: 'sessions#stepup',      via: 'get'
  match '/suggested', to: 'context#suggested',  via: 'get'
  
end

app/models/context.rb
class Context < ActiveRecord::Base

	belongs_to 	:user
	has_many						:ip_addresses
	accepts_nested_attributes_for 	:ip_addresses, allow_destroy: true, :reject_if => :all_blank

	has_many						:locations
	accepts_nested_attributes_for 	:locations, allow_destroy: true, :reject_if => :all_blank

end

app/controllers/context_controller.rb
class ContextController < ApplicationController
	def index
		@users = User.all
		@suggested_ips 			= Stepup.group(:ip, :user_id).count.select{|k,v| v > 4 && !k[0].nil?}
		@suggested_locations 	= Stepup.group(:location, :user_id).count.select{|k,v| v > 4 && !k[0].nil?}
		@suggested_times 		= Stepup.group(:time, :user_id).count.select{|k,v| v > 4 && !k[0].nil?}
	end

	def new
		
	end

	def edit
		p 			= params
		context_id	= p[:id]

		@context 	= Context.find(context_id)
		@user 		= User.find(@context.user_id)
		@loc_size	= Context.find(context_id).locations.size
		@ip_size	= Context.find(context_id).ip_addresses.size

	end

	def update
		Rails.logger.debug "params = #{params}"

		if params[:suggested]
			if (params[:suggested][/\d/].nil?)
				#remove location
				Stepup.where(:location => params[:suggested]).where(:user_id => params[:context][:user_id]).delete_all
			elsif (params[:suggested].include? ":")
				Stepup.where(:time => params[:suggested]).where(:user_id => params[:context][:user_id]).delete_all
			else
				#remove ip
				Stepup.where(:ip => params[:suggested]).where(:user_id => params[:context][:user_id]).delete_all
			end
		end



		@context 	= Context.find(params[:id])
		if @context.update_attributes(context_params)
			if (@context.starting_time == @context.ending_time)
				@context.starting_time = nil
				@context.ending_time = nil
				@context.save
			end
			redirect_to context_index_path
		else

		end
	end

	def suggested

	end

	private

		def context_params
			params.require(:context).permit(:user_id, :starting_time, :ending_time,
			locations_attributes: [:id, :location, :_destroy], ip_addresses_attributes: [:id, :ip_address, :_destroy])
		end
end

app/helpers/context_helper.rb
module ContextHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/context/edit.html.erb
    <%= form_for(setup_context(@context)) do |f| %>

      Changing log-in context for <%= @user.username %><br /><br />

      <%= f.hidden_field :user_id, value: @user.id %>


      <% if params[:time] %>        

        <% if params[:time] < @user.context.starting_time %>        
        
        <%= f.label :starting_time, "Starting Time HH:MM" %>
        <%= f.text_field :starting_time, class: 'form-control', :value => params[:time], :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>
        <%= f.label :ending_time, "Ending Time HH:MM" %>
        <%= f.text_field :ending_time, class: 'form-control', :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>

        <% elsif params[:time] > @user.context.ending_time %>

        <%= f.label :starting_time, "Starting Time HH:MM" %>
        <%= f.text_field :starting_time, class: 'form-control', :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>
        <%= f.label :ending_time, "Ending Time HH:MM" %>
        <%= f.text_field :ending_time, class: 'form-control', :value => params[:time], :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>

        <% end %>


      <% else %>

        <%= f.label :starting_time, "Starting Time HH:MM" %>
        <%= f.text_field :starting_time, class: 'form-control', :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>

        <%= f.label :ending_time, "Ending Time HH:MM" %>
        <%= f.text_field :ending_time, class: 'form-control', :pattern => '([01]?[0-9]|2[0-3]):[0-5][0-9]' %>

      <% end %>

      <br />

      <%= f.fields_for :locations do |ff| %>
        <div>
	      	<%= ff.label :location %>
          <% if (@loc_size == ff.index) %>
            <%= ff.text_field :location, :value => params[:location] %>
          <% else %>
            <%= ff.text_field :location %>
          <% end %>
	      	
          <% if ff.object.persisted? %>
      			<%= ff.check_box :_destroy %>
      			<%= ff.label :_destroy, "Delete" %>
          <% end %>
	   	  </div>
      <% end %>

      <br />

      <%= f.fields_for :ip_addresses do |ff| %>
	      <div>
	      	<%= ff.label :ip_address %>
          
          <% if (@ip_size == ff.index) %>
	      	  <%= ff.text_field :ip_address, :value => params[:ip] %>
          <% else %>
            <%= ff.text_field :ip_address %>
          <% end %>

	      	<% if ff.object.persisted? %>
      			<%= ff.check_box :_destroy %>
      			<%= ff.label :_destroy, "Delete" %>
    		<% end %>
	   	  </div>
      <% end %>     

      <br />
      
      <% if params[:location] %>
        <%= hidden_field_tag 'suggested', params[:location] %>
      <% elsif params[:ip] %>
        <%= hidden_field_tag 'suggested', params[:ip] %>
      <% elsif params[:time] %>
        <%= hidden_field_tag 'suggested', params[:time] %>
      <% end %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
<%= debug(params) if Rails.env.development? %>

app/views/context/index.html.erb
<center>
  <% if @users.empty? %>
    Geen users in database <br />
  <% else %>

  <table class="table table-striped">

    <tr class="info">
      <th>
          Username
      </th>
      <th>
          Allowed time
      </th>
      <th>
          Allowed IP(s)
      </th>
      <th>
          Allowed Location(s)
      </th>
      <% if signed_in? && current_user.admin? %>

        <th>Actions</th>

      <% end %>

    </tr>

    <% @users.each do |user| %>

    <tr>
      <td><%= user.username %> <%= user.id %></td>

      <td>
        <% if user.context.starting_time.nil? || user.context.ending_time.nil? %>
          
        <% else %>
          <%= user.context.starting_time %> - <%= user.context.ending_time %>
        <% end %>        
      </td>  

      <td>
        <% if user.context.ip_addresses.nil? %>
          nil
        <% else %>
          <% user.context.ip_addresses.each do |ip| %>
            <%= ip.ip_address %> 
          <% end %>
        <% end %>  
      </td>

      <td>
        <% if user.context.locations.nil? %>
          nil
        <% else %>
          <% user.context.locations.each do |loc| %>
            <%= loc.location %> 
          <% end %>
        <% end %>        
      </td>  

      <% if signed_in? && current_user.admin? %>

        <td>
        <div style="float:left;">
          <%= link_to "Edit", edit_context_path(user.context), :class => "btn btn-warning" %>
        </div>

      <% end %>         
    </tr>

    <% end %>

  </table>

  <h2> Suggested changes </h2>

  <% @suggested_ips.each do |key, value| %>
    <% ip   = key[0] %>
    <% user = User.find(key[1]) %> 
    
    <div>
    <%= link_to "Voeg #{ip} toe aan #{user.username}", edit_context_path(user.context, 
    :ip => ip, :user => user, :type => 0) %>
    </div>

  <% end %>

  <% @suggested_locations.each do |key, value| %>
    <% loc   = key[0] %>
    <% user = User.find(key[1]) %> 
    
    <div>
    <%= link_to "Voeg #{loc} toe aan #{user.username}", edit_context_path(user.context, 
    :location => loc, :user => user, :type => 0) %>
    </div>

  <% end %>

  <% @suggested_times.each do |key, value| %>
    <% time   = key[0] %>
    <% user = User.find(key[1]) %> 
    
    <div>
    <%= link_to "Voeg #{time} toe aan #{user.username}", edit_context_path(user.context, 
    :time => time, :user => user, :type => 0) %>
    </div>

  <% end %>

<% end %>
<br /> <br />
<%= debug(params) if Rails.env.development? %>
<%= @suggested_ips.empty? %>
</center>

app/views/context/suggested.html.erb
<%= @suggested_ips.empty? %>