config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies, only: [:new, :create, :destroy, :index, :edit]
  resources :context
  resources :users
  resources :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :admin

  get   'movies/own'  => 'movies#own'
  get   'movies/search' => 'movies#search'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/reset',   to: 'movies#reset',         via: 'get'
  match '/stepup',  to: 'sessions#stepup',      via: 'get'
  match '/suggested', to: 'context#suggested',  via: 'get'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movietrackr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/context.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Movietrackr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>        
        <%= link_to "MovieTrackr", root_path, :class => "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if !signed_in? %>

            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign Up<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for User.new do |f| %>

                      <%= f.text_field :username, :placeholder => "Username", :required => true %>

                      <!---<%= f.text_field :email, :placeholder => "Email" %>-->

                      <%= f.password_field :password, :placeholder => "Password", :required => true %><br />    
                          
                    <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>
                  
                <% end %>
              </div>
            </li>

            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for(:session, url: sessions_path) do |f| %>

                  <%= f.text_field :username, :placeholder => "Username or email" %>
             
                  <%= f.password_field :password, :placeholder => "Password" %><br />

                  <!--<%= f.text_field :otp, :placeholder => "One-Time Password" %><br />-->

                  <%= f.submit "Log in", class: "btn btn-large btn-primary" %> <br />

                <% end %>
              </div>
            </li>

          <% else %>



            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Edit profile (<%= current_user.username %>)<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for User.find(current_user.id) do |f| %>
                  <%= f.text_field :username , :readonly => true %>

                  <%= f.text_field :email, :placeholder => "Email" %>

                  <%= f.password_field :password, :placeholder => "Password", :required => true %>

                  <%= f.submit "Edit profile", class: "btn btn-large btn-primary" %>
                <% end %>
              </div>
            </li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Movies</li>
              <% if signed_in? %>

                <li><%= link_to "Add a movie", new_movie_path %></li>

                <li><%= link_to "View all movies", movies_path %></li>

                <li><%= link_to "View own movies", movies_own_path %></li>

                <% if current_user.admin? %>

                  <br />

                  <li class="nav-header">Admin options</li>

                  <li><%= link_to "Admin panel", admin_index_path %></li>

                  <li><%= link_to "Context panel", context_index_path %></li>

                <% end %>

              <% else %>

                <li><%= link_to "View all movies", movies_path %></li>               

              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; MovieTrackr 2014-2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/movies.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Movietrackr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>        
        <%= link_to "MovieTrackr", root_path, :class => "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if !signed_in? %>

            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign Up<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for User.new do |f| %>

                      <%= f.text_field :username, :placeholder => "Username", :required => true %>

                      <!---<%= f.text_field :email, :placeholder => "Email" %>-->

                      <%= f.password_field :password, :placeholder => "Password", :required => true %><br />    
                          
                    <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>
                  
                <% end %>
              </div>
            </li>

            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for(:session, url: sessions_path) do |f| %>

                  <%= f.text_field :username, :placeholder => "Username or email" %>
             
                  <%= f.password_field :password, :placeholder => "Password" %><br />

                  <!--<%= f.text_field :otp, :placeholder => "One-Time Password" %><br />-->

                  <%= f.submit "Log in", class: "btn btn-large btn-primary" %> <br />

                <% end %>
              </div>
            </li>

          <% else %>



            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Edit profile (<%= current_user.username %>)<strong class="caret"></strong></a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <%= form_for User.find(current_user.id) do |f| %>
                  <%= f.text_field :username , :readonly => true %>

                  <%= f.text_field :email, :placeholder => "Email" %>

                  <%= f.password_field :password, :placeholder => "Password", :required => true %>

                  <%= f.submit "Edit profile", class: "btn btn-large btn-primary" %>
                <% end %>
              </div>
            </li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Movies</li>
              <% if signed_in? %>

                <li><%= link_to "Add a movie", new_movie_path %></li>

                <li><%= link_to "View all movies", movies_path %></li>

                <li><%= link_to "View own movies", movies_own_path %></li>

                <% if current_user.admin? %>

                  <br />

                  <li class="nav-header">Admin options</li>

                  <li><%= link_to "Admin panel", admin_index_path %></li>

                <% end %>

              <% else %>

                <li><%= link_to "View all movies", movies_path %></li>               

              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; MovieTrackr 2014-2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>